"""Multi-prior robustness experiments for S3-Forecaster and S3-FastSketch."""

from __future__ import annotations

import copy
import time
from typing import Any, Callable, Optional

import numpy as np
import pandas as pd

from .chronos import chronos_predict_fixed_horizon, make_chronos_predictor
from .metrics import evaluate_forecast, seasonal_naive_scale
from .rolling_evaluation import evaluate_rolling_model
from .s3_fastsketch import S3FastSketchForecaster
from .s3_forecaster import S3Forecaster, SimpleFoundationProxy
from .utils import (
    count_trainable_parameters,
    ensure_series,
    make_future_index,
    parse_forecast_output,
)


class RollingPrior:
    def __init__(self, window_size: int = 6):
        self.inner = SimpleFoundationProxy(window_size=window_size)

    def fit_predict(self, series: Any, horizon: int):
        return self.inner.fit_predict(ensure_series(series), horizon)


class ETSPrior:
    def __init__(
        self,
        error: str = "add",
        trend: Optional[str] = "add",
        seasonal: Optional[str] = "add",
        seasonal_periods: Optional[int] = 12,
        damped_trend: bool = True,
    ):
        self.params = locals().copy()
        self.params.pop("self")

    def fit_predict(self, series: Any, horizon: int):
        from statsmodels.tsa.exponential_smoothing.ets import ETSModel

        y = ensure_series(series)
        params = dict(self.params)
        if params["seasonal_periods"] and len(y) < 2 * int(params["seasonal_periods"]) + 2:
            params["seasonal"] = None
            params["seasonal_periods"] = None
        result = ETSModel(y, **params).fit(disp=False)
        fitted = pd.Series(np.asarray(result.fittedvalues), index=y.index, name="fitted")
        future = pd.Series(
            np.asarray(result.forecast(horizon), dtype=float).reshape(-1),
            index=make_future_index(y, horizon),
            name="forecast",
        )
        return fitted, future


class ProphetPrior:
    def __init__(
        self,
        yearly_seasonality: bool = True,
        weekly_seasonality: bool = False,
        daily_seasonality: bool = False,
        seasonality_mode: str = "additive",
        changepoint_prior_scale: float = 0.05,
    ):
        self.params = locals().copy()
        self.params.pop("self")

    def fit_predict(self, series: Any, horizon: int):
        from prophet import Prophet

        y = ensure_series(series)
        if not isinstance(y.index, pd.DatetimeIndex):
            y.index = pd.date_range("2000-01-31", periods=len(y), freq="ME")
        frame = pd.DataFrame({"ds": y.index, "y": y.to_numpy()})
        model = Prophet(**self.params)
        model.fit(frame)
        freq = pd.infer_freq(y.index) or "ME"
        future_frame = model.make_future_dataframe(periods=horizon, freq=freq, include_history=True)
        prediction = model.predict(future_frame)
        fitted = pd.Series(prediction["yhat"].iloc[: len(y)].to_numpy(), index=y.index)
        future = pd.Series(
            prediction["yhat"].iloc[-horizon:].to_numpy(),
            index=make_future_index(y, horizon),
        )
        return fitted, future


class CallableAutoregressivePrior:
    """Adapter for Chronos, TimesFM, Moirai, TimeGPT, or custom priors.

    ``predict_fn(history, horizon)`` may return a vector, Series, or DataFrame.
    In-sample fitted values are generated by a causal walk-forward procedure.
    """

    def __init__(
        self,
        predict_fn: Callable,
        *,
        min_history: int = 24,
        fallback: str = "seasonal_naive",
        name: str = "external_prior",
    ):
        self.predict_fn = predict_fn
        self.min_history = int(min_history)
        self.fallback = fallback
        self.name = name

    def _fallback(self, history: pd.Series) -> float:
        if len(history) == 0:
            return 0.0
        if self.fallback == "last":
            return float(history.iloc[-1])
        if self.fallback == "seasonal_naive" and len(history) > 12:
            return float(history.iloc[-12])
        return float(history.mean())

    def _predict_vector(self, history: pd.Series, horizon: int) -> np.ndarray:
        output = parse_forecast_output(self.predict_fn(history, horizon)).pred
        if len(output) == horizon:
            return output.astype(float)
        current = history.copy()
        predictions = []
        for _ in range(horizon):
            one = parse_forecast_output(self.predict_fn(current, 1)).pred
            if len(one) == 0:
                raise ValueError(f"{self.name} returned an empty forecast.")
            value = float(one[-1])
            predictions.append(value)
            current.loc[make_future_index(current, 1)[0]] = value
        return np.asarray(predictions)

    def fit_predict(self, series: Any, horizon: int):
        y = ensure_series(series)
        fitted = np.zeros(len(y), dtype=float)
        for t in range(len(y)):
            history = y.iloc[:t]
            fitted[t] = (
                self._fallback(history)
                if len(history) < self.min_history
                else float(self._predict_vector(history, 1)[-1])
            )
        if len(y):
            fitted[0] = float(y.iloc[0])
        future = self._predict_vector(y, horizon)
        return (
            pd.Series(fitted, index=y.index, name="fitted"),
            pd.Series(future, index=make_future_index(y, horizon), name="forecast"),
        )


class ChronosPrior(CallableAutoregressivePrior):
    """Chronos foundation prior for robustness experiments.

    Pass ``predict_fn`` or ``model_or_factory`` for notebook/mock runs. If both
    are omitted, the prior lazily loads chronos-forecasting through
    ``ChronosZeroShotModel``.
    """

    def __init__(
        self,
        predict_fn: Optional[Callable] = None,
        *,
        model_or_factory: Any = None,
        min_history: int = 24,
        fallback: str = "seasonal_naive",
        name: str = "chronos",
        **chronos_kwargs: Any,
    ):
        predictor = make_chronos_predictor(
            model_or_factory=model_or_factory,
            predict_fn=predict_fn,
            **chronos_kwargs,
        )

        def _predict(history, horizon):
            return chronos_predict_fixed_horizon(predictor, history, horizon)

        super().__init__(
            _predict,
            min_history=min_history,
            fallback=fallback,
            name=name,
        )


def make_chronos_prior(
    predict_fn: Optional[Callable] = None,
    *,
    model_or_factory: Any = None,
    min_history: int = 24,
    fallback: str = "seasonal_naive",
    **chronos_kwargs: Any,
) -> ChronosPrior:
    return ChronosPrior(
        predict_fn=predict_fn,
        model_or_factory=model_or_factory,
        min_history=min_history,
        fallback=fallback,
        **chronos_kwargs,
    )


def evaluate_prior_only(
    prior: Any,
    train_series: Any,
    test_series: Any,
    *,
    seasonal_period: int = 12,
):
    train = ensure_series(train_series)
    test = ensure_series(test_series)
    start = time.perf_counter()
    _, forecast = prior.fit_predict(train, len(test))
    elapsed = time.perf_counter() - start
    out = parse_forecast_output(forecast)
    metrics = evaluate_forecast(
        test,
        out.pred,
        y_train=train,
        seasonal_period=seasonal_period,
        elapsed_seconds=elapsed,
        trainable_params=0,
    )
    return {"model": prior, "forecast": forecast, "metrics": metrics}


def evaluate_s3_with_prior(
    prior: Any,
    train_series: Any,
    test_series: Any,
    point_params: dict,
    *,
    uq_params: Optional[dict] = None,
    alpha: float = 0.10,
    seasonal_period: int = 12,
):
    train = ensure_series(train_series)
    test = ensure_series(test_series)
    uq = dict(uq_params or {})
    params = dict(point_params)
    if "oob_split_ratio" in params and "calibration_split_ratio" not in params:
        params["calibration_split_ratio"] = params.pop("oob_split_ratio")
    if "aci_step_size" in uq:
        params["aci_step_size"] = uq["aci_step_size"]
    minimum_width = float(uq.get("min_width_factor", 0.0)) * seasonal_naive_scale(
        train, seasonal_period=seasonal_period
    )
    model = S3Forecaster(
        horizon=1,
        target_miscoverage=(
            float(uq.get("target_miscoverage", alpha))
            if bool(uq.get("optimize_nominal_level", False))
            else float(alpha)
        ),
        interval_scale=float(uq.get("interval_scale", 1.0)),
        minimum_width=minimum_width,
        foundation=prior,
        **params,
    )
    start = time.perf_counter()
    result = evaluate_rolling_model(model, train, test, seasonal_period=seasonal_period, alpha=alpha)
    forecast = result["forecast"].copy()
    elapsed = time.perf_counter() - start
    metrics = evaluate_forecast(
        test,
        forecast["pred"],
        y_train=train,
        lower=forecast["lower"],
        upper=forecast["upper"],
        alpha=alpha,
        seasonal_period=seasonal_period,
        elapsed_seconds=elapsed,
        trainable_params=count_trainable_parameters(model),
    )
    return {"model": model, "forecast": forecast, "metrics": metrics}


def evaluate_fastsketch_with_prior(
    prior: Any,
    train_series: Any,
    test_series: Any,
    point_params: dict,
    *,
    uq_params: Optional[dict] = None,
    alpha: float = 0.10,
    seasonal_period: int = 12,
):
    train = ensure_series(train_series)
    test = ensure_series(test_series)
    uq = dict(uq_params or {})
    point_keys = {
        "foundation_window", "ar_lags", "ema_spans", "conv_scales",
        "use_calendar", "ridge_alpha", "calibration_split_ratio", "shrinkage_max",
        "prior_name", "prior__window", "prior__seasonal_period", "prior__ets_trend",
        "prior__ets_damped", "prior__theta_period", "prior__chronos_model_id",
        "prior__timesfm_model_id",
    }
    point_params = dict(point_params)
    if "oob_split_ratio" in point_params and "calibration_split_ratio" not in point_params:
        point_params["calibration_split_ratio"] = point_params.pop("oob_split_ratio")
    params = {key: value for key, value in point_params.items() if key in point_keys}
    model = S3FastSketchForecaster(
        horizon=1,
        seasonal_period=seasonal_period,
        aci_target=(
            float(uq.get("aci_target", alpha))
            if bool(uq.get("optimize_nominal_level", False))
            else float(alpha)
        ),
        aci_step_size=float(uq.get("aci_step_size", 0.05)),
        interval_scale=float(uq.get("interval_scale", 1.0)),
        minimum_width=float(uq.get("min_width_factor", 0.0)) * seasonal_naive_scale(
            train, seasonal_period=seasonal_period
        ),
        min_train_samples=6,
        min_calib_samples=2,
        use_existing_simple_foundation=False,
        **params,
    )
    model.foundation = prior
    start = time.perf_counter()
    result = evaluate_rolling_model(model, train, test, seasonal_period=seasonal_period, alpha=alpha)
    forecast = result["forecast"].copy()
    elapsed = time.perf_counter() - start
    metrics = evaluate_forecast(
        test,
        forecast["pred"],
        y_train=train,
        lower=forecast["lower"],
        upper=forecast["upper"],
        alpha=alpha,
        seasonal_period=seasonal_period,
        elapsed_seconds=elapsed,
        trainable_params=count_trainable_parameters(model),
    )
    return {"model": model, "forecast": forecast, "metrics": metrics}


def run_multi_prior_robustness(
    train_series: Any,
    test_series: Any,
    prior_factories: dict[str, Callable[[], Any]],
    *,
    s3_params: Optional[dict] = None,
    fastsketch_params: Optional[dict] = None,
    s3_uq: Optional[dict] = None,
    fastsketch_uq: Optional[dict] = None,
    include_prior_only: bool = True,
    alpha: float = 0.10,
    seasonal_period: int = 12,
):
    """Evaluate fixed model hyperparameters under alternative foundation priors."""

    rows, forecasts, models = [], {}, {}
    for prior_name, factory in prior_factories.items():
        forecasts[prior_name], models[prior_name] = {}, {}
        configurations = []
        if include_prior_only:
            configurations.append(("Prior-only", None))
        if s3_params is not None:
            configurations.append(("S3-Forecaster", s3_params))
        if fastsketch_params is not None:
            configurations.append(("S3-FastSketch", fastsketch_params))

        for model_name, params in configurations:
            prior = factory()
            try:
                if model_name == "Prior-only":
                    output = evaluate_prior_only(
                        prior, train_series, test_series, seasonal_period=seasonal_period
                    )
                elif model_name == "S3-Forecaster":
                    output = evaluate_s3_with_prior(
                        prior,
                        train_series,
                        test_series,
                        params,
                        uq_params=s3_uq,
                        alpha=alpha,
                        seasonal_period=seasonal_period,
                    )
                else:
                    output = evaluate_fastsketch_with_prior(
                        prior,
                        train_series,
                        test_series,
                        params,
                        uq_params=fastsketch_uq,
                        alpha=alpha,
                        seasonal_period=seasonal_period,
                    )
                rows.append(
                    {
                        "prior": prior_name,
                        "model": model_name,
                        "status": "ok",
                        "error": None,
                        **output["metrics"],
                    }
                )
                forecasts[prior_name][model_name] = output["forecast"]
                models[prior_name][model_name] = output["model"]
            except Exception as exc:
                rows.append(
                    {
                        "prior": prior_name,
                        "model": model_name,
                        "status": "failed",
                        "error": str(exc),
                    }
                )
                forecasts[prior_name][model_name] = None
                models[prior_name][model_name] = None

    summary = pd.DataFrame(rows).sort_values(["prior", "model"]).reset_index(drop=True)
    return {"summary": summary, "forecasts": forecasts, "models": models}


def plot_multi_prior_transferability(
    summary: pd.DataFrame,
    metric: str,
    *,
    figsize=(12, 6),
    font_size: int = 16,
    tick_size: int = 14,
    show_axis_labels: bool = False,
    show_legend: bool = False,
    color_map: Optional[dict[str, str]] = None,
    save_path: Optional[str] = None,
):
    """Plot multi-prior transferability bars with a clean no-text default."""

    import matplotlib.pyplot as plt

    valid = summary[
        (summary["status"] == "ok")
        & summary[metric].notna()
        & np.isfinite(summary[metric])
    ].copy()
    pivot = valid.pivot_table(
        index="prior",
        columns="model",
        values=metric,
        aggfunc="first",
    )

    colors = None
    if color_map:
        mapped_colors = [color_map.get(str(column)) for column in pivot.columns]
        if all(color is not None for color in mapped_colors):
            colors = mapped_colors

    fig, ax = plt.subplots(figsize=figsize)
    pivot.plot(kind="bar", ax=ax, color=colors)

    if show_axis_labels:
        ax.set_xlabel("Foundation prior", fontsize=font_size)
        ax.set_ylabel(metric.replace("_", " ").upper(), fontsize=font_size)
    else:
        ax.set_xlabel("")
        ax.set_ylabel("")

    ax.tick_params(axis="both", labelsize=tick_size)
    ax.tick_params(axis="x", rotation=0)
    ax.grid(axis="y", alpha=0.25)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    legend = ax.get_legend()
    if show_legend:
        if legend is not None:
            legend.set_title("")
            for text in legend.get_texts():
                text.set_fontsize(max(10, font_size - 4))
    elif legend is not None:
        legend.remove()

    fig.tight_layout()
    if save_path:
        fig.savefig(save_path, dpi=300, bbox_inches="tight")
    return pivot, fig, ax


def default_prior_factories(
    *,
    foundation_window: int = 6,
    include_chronos: bool = False,
    chronos_predict_fn: Optional[Callable] = None,
    chronos_model_or_factory: Any = None,
    chronos_kwargs: Optional[dict[str, Any]] = None,
    external_predictors: Optional[dict[str, Callable]] = None,
):
    factories = {
        "rolling": lambda: RollingPrior(window_size=foundation_window),
        "ets": lambda: ETSPrior(),
        "prophet": lambda: ProphetPrior(),
    }
    if include_chronos or chronos_predict_fn is not None or chronos_model_or_factory is not None:
        kwargs = dict(chronos_kwargs or {})
        factories["chronos"] = lambda: ChronosPrior(
            predict_fn=chronos_predict_fn,
            model_or_factory=chronos_model_or_factory,
            **kwargs,
        )
    for name, predictor in (external_predictors or {}).items():
        factories[name] = lambda predictor=predictor, name=name: CallableAutoregressivePrior(
            predictor, name=name
        )
    return factories
